title: KIM Hyeongi
description: Back-end Engineer
site_title: KIM Hyeongi's Portfolio

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: simlabhgkim
blog_url: .
email: gusrl401@gmail.com
keybase_username: simlabhgkim
twitter_username: simlabhgkim
reddit_username: simlabhgkim

# absolute or relative
profile_picture: assets/images/hg.jpg

# Google Analytics ID
google_analytics: 
